const CONFIG={SHEET_ID:'1yTqYEG6bM64BZiTKwgrflKw-Xfpds3CJITUdMSNowyc',SHEET_NAME:'DiaDiem'};
const GROUPS={eat:['Ăn uống','Ăn vặt - Đồ uống','Buffet - Nhà hàng'],snack:['Ăn vặt - Đồ uống'],coffee:['Cà phê'],play:['Vui chơi']};
let all=[],filtered=[],selectedCategory='',currentLat=null,currentLng=null,currentProvince='',map=null,markers=null,lastRandom='eat';
const favorites=new Set(JSON.parse(localStorage.getItem('family_places_favorites')||'[]'));
const statuses=JSON.parse(localStorage.getItem('family_places_statuses')||'{}');
const $=id=>document.getElementById(id);
function loadSheet(){window.familySheetCallback=r=>{try{if(!r||r.status==='error')throw Error('Google Sheet trả về lỗi');const t=r.table,h=(t.cols||[]).map((c,i)=>String(c.label||c.id||('C'+i)).trim());all=(t.rows||[]).map(row=>{const o={};h.forEach((k,i)=>o[k]=row.c?.[i]?.v??row.c?.[i]?.f??'');return norm(o)}).filter(x=>x.TenDiaDiem&&truthy(x.HienThi));all.forEach(x=>{if(favorites.has(x.ID))x._favorite=true;if(statuses[x.ID])x.TrangThai=statuses[x.ID]});setupProvince();render();setTimeout(requestLocation,500)}catch(e){showError(e.message)}};const s=document.createElement('script');s.src=`https://docs.google.com/spreadsheets/d/${CONFIG.SHEET_ID}/gviz/tq?tqx=${encodeURIComponent('out:json;responseHandler:familySheetCallback')}&sheet=${encodeURIComponent(CONFIG.SHEET_NAME)}&t=${Date.now()}`;s.onerror=()=>showError('Không đọc được Google Sheet');document.head.appendChild(s)}
function showError(m){$('cards').innerHTML=`<div class="empty">${esc(m)}</div>`;$('count').textContent='Lỗi dữ liệu'}
function norm(r){const x={};Object.keys(r||{}).forEach(k=>x[String(k).trim()]=String(r[k]??'').trim());x.ID=x.ID||('p-'+Math.random().toString(36).slice(2,9));x.Latitude=num(x.Latitude);x.Longitude=num(x.Longitude);x.DanhGia=Number(String(x.DanhGia||'0').replace(',','.'))||0;x._favorite=false;x._air=null;x._road=null;x._mins=null;return x}
function setupProvince(){[...new Set(all.map(x=>x.TinhThanh).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'vi')).forEach(v=>$('province').add(new Option(v,v)))}
function requestLocation(){const e=$('locationStatus');if(!navigator.geolocation){e.textContent='📍 Trình duyệt không hỗ trợ định vị';return}e.textContent='📍 Đang xác định vị trí…';navigator.geolocation.getCurrentPosition(async p=>{currentLat=p.coords.latitude;currentLng=p.coords.longitude;e.textContent=`📍 Đã định vị • sai số ±${Math.round(p.coords.accuracy||0)} m`;await detectProvince();await routes();render()},()=>e.textContent='📍 Không lấy được vị trí • hãy cho phép quyền Vị trí',{enableHighAccuracy:true,timeout:15000,maximumAge:0})}
async function detectProvince(){try{const r=await fetch(`https://nominatim.openstreetmap.org/reverse?format=jsonv2&accept-language=vi&lat=${currentLat}&lon=${currentLng}`);if(!r.ok)return;const d=await r.json(),a=d.address||{},raw=a.state||a.city||a.county||'';currentProvince=matchProvince(raw);if(currentProvince&&!$('province').value){$('province').value=currentProvince;$('locationStatus').textContent+=` • ${currentProvince}`}}catch(e){}}
function cleanProvince(s){return String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/thanh pho|tp\.?|tinh/g,'').replace(/[^a-z0-9]/g,'')}
function matchProvince(raw){const n=cleanProvince(raw),opts=[...$('province').options].map(o=>o.value).filter(Boolean);return opts.find(v=>cleanProvince(v)===n)||opts.find(v=>cleanProvince(v).includes(n)||n.includes(cleanProvince(v)))||''}
async function routes(){const items=all.filter(x=>valid(x.Latitude,x.Longitude)).slice(0,75);items.forEach(x=>x._air=hav(currentLat,currentLng,x.Latitude,x.Longitude));if(!items.length)return;try{const cs=[`${currentLng},${currentLat}`,...items.map(x=>`${x.Longitude},${x.Latitude}`)];const r=await fetch(`https://router.project-osrm.org/table/v1/driving/${cs.join(';')}?sources=0&annotations=distance,duration`);if(!r.ok)return;const d=await r.json(),ds=d.distances?.[0]||[],ts=d.durations?.[0]||[];items.forEach((x,i)=>{if(Number.isFinite(ds[i+1]))x._road=ds[i+1]/1000;if(Number.isFinite(ts[i+1]))x._mins=ts[i+1]/60})}catch(e){}}
function getFiltered(){const q=$('q').value.trim().toLowerCase(),prov=$('province').value,st=$('status').value,sort=$('sort').value;const a=all.filter(x=>{if(selectedCategory&&x.Loai!==selectedCategory)return false;if(prov&&x.TinhThanh!==prov)return false;if(st&&(x.TrangThai||'')!==st)return false;if(q&&!([x.TenDiaDiem,x.Loai,x.TinhThanh,x.QuanHuyen,x.DiaChi,x.MonAn,x.GhiChu].join(' ').toLowerCase().includes(q)))return false;return true});a.sort((a,b)=>sort==='rating'?b.DanhGia-a.DanhGia:sort==='name'?a.TenDiaDiem.localeCompare(b.TenDiaDiem,'vi'):(distance(a)??99999)-(distance(b)??99999));return a}
function distance(x){return Number.isFinite(x._road)?x._road:Number.isFinite(x._air)?x._air:null}
function render(){filtered=getFiltered();$('count').textContent=`${filtered.length} địa điểm${$('province').value?' • '+$('province').value:''}`;renderCards();renderMap()}
function renderCards(){const box=$('cards');if(!filtered.length){box.innerHTML='<div class="empty">Không có địa điểm phù hợp.</div>';return}box.innerHTML=filtered.map(x=>{const id=encodeURIComponent(x.ID);return `<article class="card"><div class="cover">${imageHtml(x)}<button class="heart" data-fav="${id}">${x._favorite?'❤️':'🤍'}</button></div><div class="body"><div class="titleRow"><div class="name">${esc(x.TenDiaDiem)}</div><div class="rating">${x.DanhGia?`⭐ ${x.DanhGia}/5`:''}</div></div><div class="meta">${esc(x.Loai||'Khác')}${x.TinhThanh?' • '+esc(x.TinhThanh):''}${x.QuanHuyen?' • '+esc(x.QuanHuyen):''}</div>${x.DiaChi?`<div class="meta">📌 ${esc(x.DiaChi)}</div>`:''}${distanceHtml(x)}${tags(x.MonAn)}${x.GhiChu?`<div class="meta">💬 ${esc(x.GhiChu)}</div>`:''}<div class="actions"><a class="btn primary" target="_blank" rel="noopener" href="${mapsUrl(x)}">🗺 Chỉ đường</a><button class="btn soft" data-map="${id}">📍 Xem map</button></div><div class="mini"><button data-status="Muốn đi" data-id="${id}">🔖 Muốn đi</button><button data-status="Đã đi" data-id="${id}">✅ Đã đi</button></div></div></article>`}).join('');box.querySelectorAll('[data-fav]').forEach(b=>b.onclick=()=>toggleFav(decodeURIComponent(b.dataset.fav)));box.querySelectorAll('[data-map]').forEach(b=>b.onclick=()=>focusMap(decodeURIComponent(b.dataset.map)));box.querySelectorAll('[data-status]').forEach(b=>b.onclick=()=>setLocalStatus(decodeURIComponent(b.dataset.id),b.dataset.status))}
function imageHtml(x){const s=imageUrl(x.HinhAnh);return s?`<img src="${attr(s)}" alt="${attr(x.TenDiaDiem)}" loading="lazy" onerror="this.replaceWith(Object.assign(document.createElement('div'),{className:'fallback',textContent:'${emoji(x.Loai)}'}))">`:`<div class="fallback">${emoji(x.Loai)}</div>`}
function imageUrl(raw){const s=String(raw||'').trim();if(!s)return'';let m;if((m=s.match(/drive\.google\.com\/file\/d\/([^/]+)/i))||(m=s.match(/[?&]id=([^&]+)/i)))return`https://drive.google.com/thumbnail?id=${m[1]}&sz=w1200`;return/^https?:\/\//i.test(s)?s:''}
function distanceHtml(x){if(Number.isFinite(x._road))return`<div class="dist">🚗 ${fmt(x._road)}${Number.isFinite(x._mins)?` • khoảng ${fmtMin(x._mins)}`:''}</div>`;if(Number.isFinite(x._air))return`<div class="dist air">📐 Đường thẳng khoảng ${fmt(x._air)}</div>`;return''}
function tags(s){const a=String(s||'').split(',').map(v=>v.trim()).filter(Boolean).slice(0,6);return a.length?`<div class="tags">${a.map(t=>`<span class="tag">${esc(t)}</span>`).join('')}</div>`:''}
function mapsUrl(x){if(valid(x.Latitude,x.Longitude))return`https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(x.Latitude+','+x.Longitude)}&travelmode=driving`;if(/^https?:\/\//i.test(x.LinkGoogleMaps||''))return attr(x.LinkGoogleMaps);return`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent([x.TenDiaDiem,x.DiaChi].filter(Boolean).join(' '))}`}
function toggleFav(id){const x=all.find(v=>v.ID===id);if(!x)return;x._favorite=!x._favorite;x._favorite?favorites.add(id):favorites.delete(id);localStorage.setItem('family_places_favorites',JSON.stringify([...favorites]));render()}
function setLocalStatus(id,s){const x=all.find(v=>v.ID===id);if(!x)return;x.TrangThai=x.TrangThai===s?'':s;x.TrangThai?statuses[id]=x.TrangThai:delete statuses[id];localStorage.setItem('family_places_statuses',JSON.stringify(statuses));render()}
function randomPick(kind){lastRandom=kind;const prov=$('province').value||currentProvince||'';let pool=all.filter(x=>(GROUPS[kind]||[]).includes(x.Loai));if(prov)pool=pool.filter(x=>x.TinhThanh===prov);if(!pool.length){$('randomTitle').textContent='🎲 Chưa có địa điểm phù hợp';$('randomResult').innerHTML=`<div class="pick">Không có địa điểm thuộc nhóm này${prov?' tại '+esc(prov):''}.</div>`;$('randomDialog').showModal();return}const x=pool[Math.floor(Math.random()*pool.length)],titles={eat:'🎲 Hôm nay Winbi ăn gì?',snack:'🥤 Ăn vặt / uống gì?',coffee:'☕ Cà phê ở đâu?',play:'🎡 Hôm nay Winbi đi đâu?'};$('randomTitle').textContent=titles[kind];$('randomResult').innerHTML=`<div class="pick"><div class="name">${esc(x.TenDiaDiem)}</div><div class="meta">${esc(x.Loai)}${x.TinhThanh?' • '+esc(x.TinhThanh):''}${x.QuanHuyen?' • '+esc(x.QuanHuyen):''}</div>${distanceHtml(x)}<div style="margin-top:10px"><a class="btn primary" target="_blank" rel="noopener" href="${mapsUrl(x)}">🗺 Đi thôi</a></div></div>`;$('randomDialog').showModal()}
function setView(v){$('listView').classList.toggle('hidden',v!=='list');$('mapView').classList.toggle('hidden',v!=='map');$('tabList').classList.toggle('active',v==='list');$('tabMap').classList.toggle('active',v==='map');if(v==='map')setTimeout(()=>{initMap();renderMap();map.invalidateSize()},60)}
function initMap(){if(map)return;map=L.map('map').setView([15.8,106.7],6);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap contributors'}).addTo(map);markers=L.layerGroup().addTo(map)}
function renderMap(){if(!map||!markers)return;markers.clearLayers();const b=[];filtered.forEach(x=>{if(!valid(x.Latitude,x.Longitude))return;L.marker([x.Latitude,x.Longitude]).addTo(markers).bindPopup(`<strong>${esc(x.TenDiaDiem)}</strong><br>${esc(x.Loai||'')}<br><a target="_blank" href="${mapsUrl(x)}">Google Maps</a>`);b.push([x.Latitude,x.Longitude])});if(currentLat!==null){L.circleMarker([currentLat,currentLng],{radius:8,weight:3,fillOpacity:.8}).addTo(markers).bindPopup('Vị trí hiện tại');b.push([currentLat,currentLng])}if(b.length)map.fitBounds(b,{padding:[30,30],maxZoom:15})}
function focusMap(id){const x=all.find(v=>v.ID===id);if(!x||!valid(x.Latitude,x.Longitude))return;setView('map');setTimeout(()=>map.setView([x.Latitude,x.Longitude],16),100)}
function num(v){let s=String(v??'').trim().replace(',','.');const n=Number(s);return Number.isFinite(n)?n:null}function valid(a,b){return Number.isFinite(a)&&Number.isFinite(b)&&Math.abs(a)<=90&&Math.abs(b)<=180}function hav(a,b,c,d){const R=6371,r=Math.PI/180,q=Math.sin((c-a)*r/2)**2+Math.cos(a*r)*Math.cos(c*r)*Math.sin((d-b)*r/2)**2;return R*2*Math.atan2(Math.sqrt(q),Math.sqrt(1-q))}function fmt(k){return k<1?`${Math.round(k*1000)} m`:`${k.toFixed(k<10?1:0)} km`}function fmtMin(m){return m<60?`${Math.round(m)} phút`:`${Math.floor(m/60)} giờ ${Math.round(m%60)} phút`}function truthy(v){return v===true||['TRUE','1','YES','CÓ','CO'].includes(String(v||'').trim().toUpperCase())}function emoji(t){return t==='Cà phê'?'☕':t==='Vui chơi'?'🎡':t==='Ăn vặt - Đồ uống'?'🥤':t==='Buffet - Nhà hàng'?'🍲':t==='Ăn uống'?'🍜':'📍'}function esc(s){return String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')}function attr(s){return esc(s)}
document.addEventListener('DOMContentLoaded',()=>{$('locBtn').onclick=requestLocation;$('q').oninput=render;$('province').onchange=render;$('status').onchange=render;$('sort').onchange=render;$('chips').querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>{selectedCategory=b.dataset.cat;document.querySelectorAll('.chip').forEach(c=>c.classList.remove('active'));b.classList.add('active');render()});document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));$('randomEatBtn').onclick=()=>randomPick('eat');$('randomSnackBtn').onclick=()=>randomPick('snack');$('randomCoffeeBtn').onclick=()=>randomPick('coffee');$('randomPlayBtn').onclick=()=>randomPick('play');$('rerollBtn').onclick=()=>randomPick(lastRandom);$('closeRandomBtn').onclick=()=>$('randomDialog').close();loadSheet()});